name: pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          headless: true
  
  # to parallelize tests executions 
  cypress-config-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cypress-config: ["a", "c"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          spec: "**/${{ matrix.cypress-config }}*.js"
          headless: true

  cypress-docker:
    runs-on: ubuntu-latest
    container: cypress/included:4.9.0
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cypress.json
          headless: true

  cypress-docker-npm:
    # needs directive to have a synchronous example
    needs: [cypress-docker]
    runs-on: ubuntu-latest
    container: cypress/included:4.9.0
    steps:
      - uses: actions/checkout@v2.3.4
      # npm ci only for cypress-cucumber plugin that is present in plugins/index.js
      # if no install, cannot find module error is thrown
      - run: npm ci
      - run: npm run cy:run

  cucumber:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cucumber.json
          headless: true

  cucumber-config-matrix:
    needs: [cucumber]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cucumber-config: ["ac", "al"]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          config-file: cucumber.json
          spec: "**/${{ matrix.cucumber-config }}*.feature"
          headless: true
